[package]
name = 'tchpad'
version = '0.0.0'
edition = '2021'

[dependencies]
cairo-rs = '0.14'
glib-sys = '0.14'
regex = '1.5'
xcb = '0.10'

[dependencies.rofi-sys]
path = 'rofi-sys'

[dependencies.xcb-util]
features = ['ewmh', 'icccm']
version = '0.4'

[lib]
crate-type = ['cdylib']
